### ISSUE TITLE
CSS style

### ISSUE THREAD

**Issue by stevetoro** [damianhagger/prj-rev-bwfs-dasmoto#4]
https://github.com/damianhagger/prj-rev-bwfs-dasmoto/blob/master/DasMoto-DamianHagger/resources/css/main.css#L19-L21

Try to avoid writing your CSS rules like this. Even if you only have a single style in your rule, you should still write it like so:

```css
.green {
  background-color: mediumspringgreen;
}
```

This makes it easier for your fellow programmers to understand what's going on and debug your code, as well as scale your stylesheet as more complicated styles need to be implemented.
